package geso.traphaco.erp.beans.kiemdinhchatluong.kho;

import java.sql.ResultSet;
import java.util.List;

import geso.traphaco.center.db.sql.dbutils;
import geso.traphaco.erp.beans.kiemdinhchatluong.kho.imp.KiemDinhObj;

public interface IErpKiemDinhChatLuongKho {
	public String getUserId();
	public void setUserId(String userId);
	public String getId();
	public void setId(String id);
	public String getSpId();
	public void setSpId(String spId);
	public String getSoLuongKiemDinh();
	public void setSoLuongKiemDinh(String soLuongKiemDinh);
	public String getSoluongDat();
	public void setSoluongDat(String soluongDat);
	public String getDatCl();
	public void setDatCl(String datCl) ;
	public String getTongsoluongnhap();
	public void setTongsoluongnhap(String tongsoluongnhap);
	public String getSoluongchuakiem();
	public void setSoluongchuakiem(String soluongchuakiem);
	public String getCongtyId();
	public void setCongtyId(String congtyId);
	public String getTrangthai();
	public void setTrangthai(String trangthai);
	public String getNgaykiem();
	public void setNgaykiem(String ngaykiem);
	public String getMsg();
	public void setMsg(String msg);
	public ResultSet getKhoRs();
	public void setKhoRs(ResultSet khoRs);
	public ResultSet getRsSanPham();
	public void setRsSanPham(ResultSet rsSanPham);
	public String getDenghixuly();
	public void setDenghixuly(String denghixuly);
	public String getSoluongmau();
	public void setSoluongmau(String soluongmau);
	public dbutils getDb();
	public void setDb(dbutils db);
	public ResultSet getRsSoThung();
	public void setRsSoThung(ResultSet rsSoThung);
	public String[] getListSoThung();
	public void setListSoThung(String[] listSoThung);
	public String[] getListSoLuongThung();
	public void setListSoLuongThung(String[] listSoLuongThung);
	public String[] getListLayMauThung();
	public void setListLayMauThung(String[] listLayMauThung);
	public String[] getListDatThung();
	public void setListDatThung(String[] listDatThung);
	public String[] getListKhongDatThung();
	public void setListKhongDatThung(String[] listKhongDatThung);
	public String[] getListHamAm();
	public void setListHamAm(String[] listHamAm);
	public String[] getListHamLuong();
	public void setListHamLuong(String[] listHamLuong);
	public String[] getListKhoChiTiet();
	public void setListKhoChiTiet(String[] listKhoChiTiet);
	public String getLoaimh();
	public void setLoaimh(String loaimh);
	public String getMaPhieu();
	public void setMaPhieu(String maPhieu);
	public String getMaMe();
	public void setMaMe(String maMe) ;
	public String getKhoId();
	public void setKhoId(String khoId);
	public String getSoLo();
	public void setSoLo(String soLo);
	public void init();
	public boolean update();
	public boolean create();
	public void createRs();
	public boolean duyetKiemDinh();
	public void DbClose();
	public List<KiemDinhObj> getListSpKiemDinh();
	public void setListSpKiemDinh(List<KiemDinhObj> listSpKiemDinh);
}	
